local export = {}

export.title = "Ainu dialectal forms of %s"

export.columns = {
	"Group",
	"Region",
	"Location",
	"Words",
}

export.notes = {
	"This table shows various dialectal forms in Ainu languages. The classification into Hokkaido, Sakhalin, and Kuril groups is based on geographical distribution.",
	"((CW)): 知里真志保・和田文治郎（1943）「樺太アイヌ語に於ける人体関係名彙」『樺太庁博物館報告』5(1): 39-80",
	"((C1)): 知里真志保（1953）『分類アイヌ語辞典. 第1巻 (植物篇)』日本常民文化研究所", 
	"((C3)): 知里真志保（1954）『分類アイヌ語辞典. 第3巻 (人間篇)』日本常民文化研究所",
	"((HC)): 服部四郎・知里真志保（1960）「アイヌ語諸方言の基礎語彙統計学的研究」『民族學研究』24(4): 307-342，日本文化人類学会",
	"((C2)): 知里真志保（1962）『分類アイヌ語辞典. 第2巻 (動物篇)』日本常民文化研究所", 
	"((H)): 服部四郎 編（1964）『アイヌ語方言辞典』岩波書店",
	"((V)): Alexander Vovin (1993) A Reconstruction of Proto-Ainu. Leiden: E.J. Brill",
	"((F2016)): 深澤美香（2016）「〈資料紹介〉加賀家文書「［蝦夷語和解］」―蝦夷通辞・加賀伝蔵による『藻汐草』の語釈本―」千葉大学大学院人文社会科学研究科研究プロジェクト報告書 298: 81",
	"((K2021)): 釧路アイヌ語の会 編（2021）『釧路地方のアイヌ語語彙集』藤田印刷エクセレントブックス",
	"((BS)): Anna Bugaeva and Tomomi Sato (2021) A Kuril Ainu Glossary by Captain V. M. Golovnin (1811). International Journal of Eurasian Linguistics 3(2): 171-216",
}

export.varieties = {
	{
		name = "Honshu",
		text_display = "Honshu Matagi",
		color = "var(--wikt-palette-blue-1)",
		{
			-- This group represents the Matagi regions on Honshu island.
			{ name = "Ani", japanese = "阿仁", text_display = "[[w:ja:阿仁町|Ani]]", lat = 39.99, long = 140.40 },
			{ name = "Senboku", japanese = "仙北", text_display = "[[w:Daisen, Akita|Senboku]]", lat = 39.45, long = 140.47 },
			{ name = "Meya", japanese = "目屋", text_display = "[[w:Nishimeya, Aomori|Meya]]", lat = 40.56, long = 140.29 },
			{ name = "Matagi", japanese = "マタギ", text_display = "Matagi", lat = 40.0, long = 140.39 },
		}
	},
	{
		name = "Hokkaido",
		text_display = "Hokkaido Ainu",
		code = "ain-hok",
		color = "var(--wikt-palette-red-1)",
		{
			name = "DonanDoo",
			text_display = "Southern/Central",
			color = "var(--wikt-palette-red-1)",
			{ name = "Abuta", japanese = "虻田", text_display = "[[w:Abuta District, Hokkaido|Abuta]]", lat = 42.75, long = 140.81 },
			{ name = "Azuma", japanese = "厚真", text_display = "[[w:Atsuma, Hokkaido|Azuma]]", lat = 42.72, long = 141.88 },
			{ name = "Biratori", japanese = "平取", text_display = "[[w:Biratori, Hokkaido|Biratori]]", lat = 42.59, long = 142.14 },
			{ name = "Chitose", japanese = "千歳", text_display = "[[w:Chitose, Hokkaido|Chitose]]", lat = 42.82, long = 141.65 },
			{ name = "Ebeotsu", japanese = "江部乙", text_display = "[[w:ja:江部乙|Ebeotsu]]", lat = 43.59, long = 141.97 },
			{ name = "Hagino", japanese = "萩野", text_display = "[[w:Shiraoi, Hokkaido|Hagino]]", lat = 42.54, long = 141.3 },
			{ name = "Hidaka", japanese = "日高", text_display = "[[w:Hidaka, Hokkaido|Hidaka]]", lat = 42.48, long = 142.16 },
			{ name = "Hobetsu", japanese = "穂別", text_display = "[[w:Hobetsu, Hokkaido|Hobetsu]]", lat = 42.77, long = 142.1 },
			{ name = "Horobetsu", japanese = "幌別", text_display = "[[w:Noboribetsu|Horobetsu]]", lat = 42.42, long = 141.11 },
			{ name = "Horoman", japanese = "幌満", text_display = "[[w:Samani, Hokkaido|Horoman]]", lat = 42.13, long = 142.92 },
			{ name = "Mitsuishi", japanese = "三石", text_display = "[[w:Mitsuishi, Hokkaido|Mitsuishi]]", lat = 42.26, long = 142.58 },
			{ name = "Mukawa", japanese = "鵡川", text_display = "[[w:Mukawa, Hokkaido|Mukawa]]", lat = 42.6, long = 141.93 },
			{ name = "Muroran", japanese = "室蘭", text_display = "[[w:Muroran, Hokkaido|Muroran]]", lat = 42.32, long = 140.98 },
			{ name = "Niikappu", japanese = "新冠", text_display = "[[w:Niikappu, Hokkaido|Niikappu]]", lat = 42.35, long = 142.33 },
			{ name = "Nukkibetsu", japanese = "貫気別", text_display = "[[w:Biratori, Hokkaido|Nukkibetsu]]", lat = 42.64, long = 142.29 },
			{ name = "Ogifushi", japanese = "荻伏", text_display = "Ogifushi", lat = 42.23, long = 142.71 },
			{ name = "Oshamambe", japanese = "長万部", text_display = "[[w:Oshamanbe, Hokkaido|Oshamambe]]", lat = 42.51, long = 140.38 },
			{ name = "Rebun", japanese = "礼文", text_display = "[[w:Rebun, Hokkaido|Rebun]]", lat = 42.59, long = 140.59 },
			{ name = "Samani", japanese = "様似", text_display = "[[w:Samani, Hokkaido|Samani]]", lat = 42.13, long = 142.92 },
			{ name = "Saru", japanese = "沙流", text_display = "[[w:Saru District, Hokkaido|Saru]]", lat = 42.59, long = 142.14 },
			{ name = "Shiraoi", japanese = "白老", text_display = "[[w:Shiraoi, Hokkaido|Shiraoi]]", lat = 42.55, long = 141.35 },
			{ name = "Shizunai", japanese = "静内", text_display = "[[w:Shizunai, Hokkaido|Shizunai]]", lat = 42.33, long = 142.37 },
			{ name = "Takae", japanese = "高江", text_display = "[[w:Niikappu, Hokkaido|Takae]]", lat = 42.35, long = 142.33 },
			{ name = "Takashima", japanese = "高島", text_display = "Takashima", lat = 43.05, long = 143.46 },
			{ name = "Toyoura", japanese = "豊浦", text_display = "[[w:Toyoura, Hokkaido|Toyoura]]", lat = 42.58, long = 140.73 },
			{ name = "Urakawa", japanese = "浦河", text_display = "[[w:Urakawa, Hokkaido|Urakawa]]", lat = 42.17, long = 142.77 },
			{ name = "Usu", japanese = "有珠", text_display = "[[w:Usu District, Hokkaido|Usu]]", lat = 42.52, long = 140.84 },
			{ name = "Kunen", japanese = "空念", text_display = "Kunen", lat = 42.25, long = 140.27 },
			{ name = "Yakumo", japanese = "八雲", text_display = "[[w:Yakumo, Hokkaido|Yakumo]]", lat = 42.25, long = 140.27 },
		},
		{
			name = "Dohoku",
			text_display = "Northern",
			color = "var(--wikt-palette-red-3)",
			{ name = "Asahikawa", japanese = "旭川", text_display = "[[w:Asahikawa, Hokkaido|Asahikawa]]", lat = 43.77, long = 142.36 },
			{ name = "Chikabumi", japanese = "近文", text_display = "[[w:Takasu, Hokkaido|Chikabumi]]", lat = 43.77, long = 142.36 },
			{ name = "Nayoro", japanese = "名寄", text_display = "[[w:Nayoro, Hokkaido|Nayoro]]", lat = 44.35, long = 142.46 },
			{ name = "Soya", japanese = "宗谷", text_display = "[[w:Soya Subprefecture|Soya]]", lat = 45.52, long = 141.96 },
			{ name = "Teshio", japanese = "天塩", text_display = "[[w:Teshio, Hokkaido|Teshio]]", lat = 44.9, long = 141.75 },
		},
		{
			name = "Doto",
			text_display = "Eastern",
			color = "var(--wikt-palette-red-4)",
			{ name = "Abashiri", japanese = "網走", text_display = "[[w:Abashiri, Hokkaido|Abashiri]]", lat = 44.02, long = 144.27 },
			{ name = "Akan", japanese = "阿寒", text_display = "[[w:Akan, Hokkaido|Akan]]", lat = 43.45, long = 144.15 },
			{ name = "Ashoro", japanese = "足寄", text_display = "[[w:Ashoro, Hokkaido|Ashoro]]", lat = 43.25, long = 143.55 },
			{ name = "Bihoro", japanese = "美幌", text_display = "[[w:Bihoro, Hokkaido|Bihoro]]", lat = 43.83, long = 144.11 },
			{ name = "Biroo", japanese = "広尾", text_display = "[[w:Hiroo, Hokkaido|Biroo]]", lat = 42.29, long = 143.32 },
			{ name = "Chirotto", japanese = "白人", text_display = "[[w:Makubetsu, Hokkaido|Chirotto]]", lat = 42.89, long = 143.32 },
			{ name = "Fupushinai", japanese = "布伏内", text_display = "[[w:Akan, Hokkaido|Fupushinai]]", lat = 43.2, long = 144 },
			{ name = "Fushiko", japanese = "伏古", text_display = "[[w:ja:伏古村|Fushiko]]", lat = 42.92, long = 143.18 },
			{ name = "Harutori", japanese = "春採", text_display = "[[w:ja:春採湖|Harutori]]", lat = 42.99, long = 144.38 },
			{ name = "Kitami", japanese = "北見", text_display = "[[w:Kitami, Hokkaido|Kitami]]", lat = 43.8, long = 143.89 },
			{ name = "Kushiro", japanese = "釧路", text_display = "[[w:Kushiro, Hokkaido|Kushiro]]", lat = 42.99, long = 144.38 },
			{ name = "Kussharo", japanese = "屈斜路", text_display = "[[w:Lake Kussharo|Kussharo]]", lat = 43.56, long = 144.32 },
			{ name = "Memuro", japanese = "芽室", text_display = "[[w:Memuro, Hokkaido|Memuro]]", lat = 42.91, long = 143.05 },
			{ name = "Mokoto", japanese = "藻琴", text_display = "[[w:ja:藻琴村|Mokoto]]", lat = 43.95, long = 144.3 },
			{ name = "Nemuro", japanese = "根室", text_display = "[[w:Nemuro, Hokkaido|Nemuro]]", lat = 43.32, long = 145.58 },
			{ name = "Nijibetsu", japanese = "虹別", text_display = "[[w:Shibecha, Hokkaido|Nijibetsu]]", lat = 43.46, long = 144.73 },
			{ name = "Obihiro", japanese = "帯広", text_display = "[[w:Obihiro, Hokkaido|Obihiro]]", lat = 42.92, long = 143.2 },
			{ name = "Otofuke", japanese = "音更", text_display = "[[w:Otofuke, Hokkaido|Otofuke]]", lat = 42.99, long = 143.2 },
			{ name = "Shari", japanese = "斜里", text_display = "[[w:Shari, Hokkaido|Shari]]", lat = 43.91, long = 144.67 },
			{ name = "Shiranuka", japanese = "白糠", text_display = "[[w:Shiranuka, Hokkaido|Shiranuka]]", lat = 42.96, long = 144.08 },
			{ name = "Tokachi", japanese = "十勝", text_display = "[[w:Tokachi Subprefecture|Tokachi]]", lat = 42.91, long = 143.69 },
			{ name = "Tooro", japanese = "塘路", text_display = "Tooro", lat = 43.16, long = 144.57 },
		},
	},
	{
		name = "Sakhalin",
		text_display = "Sakhalin Ainu",
		code = "ain-sak",
		color = "var(--wikt-palette-green-1)",
		{
			name = "WestCoast",
			text_display = "West Coast",
			color = "var(--wikt-palette-green-1)",
			{ name = "Chirai", japanese = "智来", text_display = "Chirai", lat = 47.98, long = 142.09 },
			{ name = "Maoka", japanese = "真岡", text_display = "[[w:Kholmsk|Maoka]]", lat = 47.19, long = 142.12 },
			{ name = "Raichishka", japanese = "ライチシカ", text_display = "[[w:Uglegorsk, Sakhalin Oblast|Raichishka]]", lat = 48.81, long = 141.95 },
			{ name = "Shiranushi", japanese = "白主", text_display = "Shiranushi", lat = 45.96, long = 142.06 },
			{ name = "Tarantomari", japanese = "多蘭泊", text_display = "[[w:Korsakov (town)|Tarantomari]]", lat = 47.07, long = 142.06 },
			{ name = "Usoro", japanese = "鵜城", text_display = "Usoro", lat = 49.08, long = 141.96 },
		},
		{
			name = "EastCoast",
			text_display = "East Coast",
			color = "var(--wikt-palette-green-2)",
			{ name = "Aihama", japanese = "相浜", text_display = "Aihama", lat = 47.57, long = 142.73 },
			{ name = "Nairo", japanese = "内路", text_display = "Nairo", lat = 49.27, long = 142.93 },
			{ name = "Niitoi", japanese = "新問", text_display = "Niitoi", lat = 49.11, long = 143.02 },
			{ name = "Ochiho", japanese = "落帆", text_display = "Ochiho", lat = 46.99, long = 143.19 },
			{ name = "Shirahama", japanese = "白浜", text_display = "Shirahama", lat = 47.56, long = 142.7 },
			{ name = "Shiraura", japanese = "白浦", text_display = "Shiraura", lat = 47.95, long = 142.53 },
			{ name = "Taraika", japanese = "多来加", text_display = "[[w:Poronaysk|Taraika]]", lat = 49.54, long = 143.68 },
			{ name = "Tonnai", japanese = "富内", text_display = "Tonnai", lat = 46.99, long = 143.19 },
			{ name = "Yamambetsu", japanese = "弥満別", text_display = "[[w:Yamambetsu, Sakhalin|Yamambetsu]]", lat = 46.42, long = 143.46 },
		},
	},
	{
		name = "Kuril",
		text_display = "Kuril Ainu",
		code = "ain-kur",
		color = "var(--wikt-palette-yellow-1)",
		{
			name = "Hokubu",
			text_display = "Northern",
			color = "var(--wikt-palette-orange-1)",
			{ name = "Kuril", japanese = "千島", text_display = "[[w:Kuril Islands|Kuril]]", lat = 50.73, long = 156.32 },
			{ name = "Paramushir", japanese = "幌筵", text_display = "[[w:Paramushir|Paramushir]]", lat = 50.55, long = 155.98 },
			{ name = "Shumshu", japanese = "占守", text_display = "[[w:Shumshu|Shumshu]]", lat = 50.73, long = 156.32 },
		},
		{
			name = "Nambu",
			text_display = "Southern",
			color = "var(--wikt-palette-orange-2)",
			{ name = "Etorofu", japanese = "択捉", text_display = "[[w:Iturup|Etorofu]]", lat = 45, long = 147.88 },
			{ name = "South Kuril", japanese = "南千島", text_display = "[[w:Kuril Islands dispute|South Kuril]]", lat = 44.25, long = 146.68 },
		},
	},
}

return export
